### ISSUE TITLE
`[operator []]` breaking in dartdoc w/ latest

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/markdown#216]
From this source: https://github.com/dart-lang/sdk/blob/86ba29265a3b8c2198a6562c0b826af873202da6/sdk/lib/async/zone.dart#L391

Running dartdoc head w/ markdown @ head yields this diff

```diff
-<p>The new zone inherits the stored values (accessed through <a href="dart-async/Zone/operator_get.html">operator []</a>)
+<p>The new zone inherits the stored values (accessed through [operator <code></code>])
```

**Comment by srawlins** [comment]
This used to work? :frowning_face: Bah! I'll look at this ASAP.

**Comment by kevmoo** [comment]
I was hoping https://github.com/dart-lang/markdown/issues/213 was the ticket.

CC @jcollins-g – keep in mind, dartdoc does it's own customization on top of markdown for links and things – there could just be a funky interaction. Not sure...

**Comment by srawlins** [comment]
This is more-or-less working as intended. I think just a slight fix is needed in dartdoc's resolver:

If the text passed to the custom resolver is empty, return null. So the problem is that `[operator []]` gets to the first `]`, and tries to resolve `[]` with the custom resolver. The custom resolver receives the text `""`, shrugs, and returns `<code></code>`. It should instead return null. The null will trigger the markdown parser to say that `[]` must just be text, then will reach the second `]`, and try to resolve `[operator []]` with the custom resolver.

I'm sending a PR anyways with a new test case.

**Comment by kevmoo** [comment]
Thanks for digging in, Sam!

**Comment by kevmoo** [comment]
I understand now. Let's ship v2!
