### ISSUE TITLE
Consistent Output

### ISSUE THREAD

**Issue by caffinatedmonkey** [dart-lang/markdown#27]
Currently, the parser places new lines where it shouldn't. Here is an example: https://drone.io/github.com/caffinatedmonkey/dart-markdown/3

Either the output should have no newlines or it should preserve newlines.

**Comment by munificent** [comment]
Most Markdown parsers do not precisely specify what whitespace they output when outputting HTML. For example, the CommonMark test suite [normalizes out whitespace changes](https://github.com/jgm/CommonMark/blob/master/test/normalize.py) when validating expected output.

Producing *no* newlines makes for painful output when you open it in a text editor. Precisely preserving all of the original newlines would be very difficult if not impossible, since some of them may be meaningful to Markdown itself and get consumed for that purpose.
