### ISSUE TITLE
Change in behaviour between `markdown: 4.0.0` and `markdown: 5.0.0`

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/markdown#414]
Test code:

```dart
import 'package:markdown/markdown.dart';

void main() {
  final document = Document(encodeHtml: false).parseInline(r'[link](<foo\>)');
  print(document[0].textContent);
}
```

Results with Markdown 4.0.0

```console
[link](<foo&gt;)
```

Results with Markdown 5.0.0

```console
[link](<foo>)
```

Context: This change in behaviour is failing the [pointy brackets that enclose links must be unescaped](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/test/link_test.dart#L390) test in the `flutter_markdown` package when attempting to update dependency: https://github.com/flutter/packages/pull/1395

**Comment by chenzhiguang** [comment]
Maybe should change https://github.com/flutter/packages/blob/main/packages/flutter_markdown/test/link_test.dart#L407  to `expectInvalidLink('[link](<foo>)');`

There was an issue in markdown 4.0, `EscapeSyntax` ignored `encodeHtml` and always parsed `>` to `&gt;` no matter `encodeHtml` is `true` or `false`. This issue has been fixed in https://github.com/dart-lang/markdown/pull/386

**Comment by domesticmouse** [comment]
SGTM, thanks!
