### ISSUE TITLE
CommonMark compliance

### ISSUE THREAD

**Issue by Scorpiion** [dart-lang/markdown#51]
Hi,

Is there a plan for this package to become "CommonMark compliant" or is the intention to follow some specific (or it's own) flavor of Markdown?

I have been using a different Dart package, md_proc, simply because it claims to be CommonMark compliant. Not sure how these two package differs, but if this package also intends to become CommonMark compliant maybe there are some "synergies" to be found between the two: 
https://github.com/dikmax/md_proc

**Comment by srawlins** [comment]
My intention would be for this package to be come CommonMark compliant, and run it against the CommonMark specs.

md_proc looks like a very full-featured Markdown parser! Very cool project. Not sure what opportunities for "synergies" there would be though...

**Comment by Scorpiion** [comment]
Okay, yes I would like that too. I think it's nice if the parser would follow a clear spec.

Yeah I know, but it's a good reference at least. Maybe some of the tests against the spec could be reused or base new tests upon them to save at least a little bit of time.

**Comment by kevmoo** [comment]
FYI – I've added some tooling to at least validate this impl against CommonMark - https://github.com/dart-lang/markdown/commit/a7db5a63b6b6fd640fb7fd6ce49138df16851f16

We fail a lot of these – but at least we have a way to track our compliance

**Comment by mehaase** [comment]
Comparing test cases as strings won't work because the test cases contain HTML attributes in arbitrary orders, e.g.: 

    {
      "section": "Images",
      "end_line": 7244,
      "markdown": "![foo](/url \"title\")\n",
      "start_line": 7240,
      "html": "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n",
      "example": 521
    },

The `HtmlRenderer` in this library sorts attribute names alphabetically, so it will never produce "src" before "alt".

**Comment by kevmoo** [comment]
Would it be better if `HtmlRender` *didn't* sort the elements?

**Comment by mehaase** [comment]
There's probably no good reason to sort attributes, but the unit tests currently depend on attribute order so additional work is needed if attributes are not sorted.

**Comment by kevmoo** [comment]
@mehaase I just went through to see if sorting affects any of the common-mark tests. I doesn't seem that it does.

If it comes up as a spec compliance thing, I'd consider it – otherwise I'd like to avoid adding noise to the implementation.

**Comment by mehaase** [comment]
> @mehaase do you have an example where a common-mark test is failing just because of the ordering of attributes?

To answer your question from the PR, yes test case 521 (it's a few posts up in this thread). Here are the expected and actual outputs for that test case as it stands on `master` right now.

Expected:

    <p><img src="/url" alt="foo" title="title" /></p>

Actual:

    <p><img alt="foo" src="/url" title="title" /></p>

There are other test cases that rely on attribute order. Most of them are anchors that happen to have attributes in alphabetical order (`href` before `title`). The image test cases have `src` before `alt`, which will definitely cause test failures, but nobody noticed before because the image test cases were totally broken for other reasons.

The far, far more common issue, however, is insignificant whitespace. For example, test case 4:

Expected:

    <ul>
    <li>
    <p>foo</p>
    <p>bar</p>
    </li>
    </ul>

Actual:

    <ul><li>
    <p>foo</p>
    <p>bar</p></li></ul>

It's the exact same DOM. The whitespace between `<ul>` and `<li>`, for example, is insignificant. 

**Over 150 CommonMark tests fail due to insignificant differences in the markup.** Moreover, you'll *never get these tests right* unless you normalize the HTML output somehow.

**Comment by srawlins** [comment]
I'm going to close this, as it's been well discussed. In closing: we are aiming for CommonMark compliance as the standard. We're now passing 463/613 (75%) CommonMark v0.24 specs.

Many of the remaining ones are edge cases (like the Autolink failures), or the [17 crazy emphasis and strong emphasis rules](http://spec.commonmark.org/0.24/#emphasis-and-strong-emphasis). Our weak categories (according to raw spec numbers) are:

* Lists - only 16% passing (I think this is mostly paragraphing and nesting rules)
* List items - only 53% passing
* Link reference definitions - only 57% passing
* Autolinks - only 58% passing
* Setext headings - only 61% passing

We'll continue to try to improve these, but I don't think any are considered high priority, without a specific bug from a user with a real use case.
